---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: foundryvtt
    container_name: foundryvtt
    restart: "no"
    volumes:
      - type: bind
        source: ./data
        target: /data
    env_file: .env
    ports:
      - "30000:30000"
