---
version: "3.7"

secrets:
  fullchain_pem:
    file: ./src/secrets/fullchain.pem
  privkey_pem:
    file: ./src/secrets/privkey.pem
  mailarchive_passwd_txt:
    file: ./src/secrets/mailarchive_passwd.txt


services:
  postfix:
    build:
      context: .
      dockerfile: Dockerfile
    image: dhsncats/postfix
    init: true
    restart: always
    environment:
      - PRIMARY_DOMAIN=example.com
      - RELAY_IP=172.16.202.1/32
    networks:
      front:
        ipv4_address: 172.16.202.2
    ports:
      - target: "25"
        published: "1025"
        protocol: tcp
        mode: host
      - target: "587"
        published: "1587"
        protocol: tcp
        mode: host
      - target: "993"
        published: "1993"
        protocol: tcp
        mode: host
    secrets:
      - source: fullchain_pem
        target: fullchain.pem
      - source: privkey_pem
        target: privkey.pem
      - source: mailarchive_passwd_txt
        target: mailarchive_passwd.txt

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.202.0/24
