---
version: "3.8"

services:
  foundry:
    image: foundry:latest
    build:
      context: . 
    hostname: foundry
    container_name: foundry
    restart: unless-stopped
    volumes:
      - ./data:/data/foundryvtt
      #- ./app:/opt/foundryvtt/resources/app
    ports:
      - "30000:30000"
