---
version: "3.7"

secrets:
  quote_txt:
    file: ./src/secrets/quote.txt

services:
  example:
    build:
      context: .
      dockerfile: Dockerfile
    image: dhsncats/example
    init: true
    restart: on-failure
    environment:
      - ECHO_MESSAGE=Hello World from docker-compose!
    ports:
      - target: "8080"
        published: "8080"
        protocol: tcp
        mode: host
    secrets:
      - source: quote_txt
        target: quote.txt
