---
version: "3.7"

volumes:
  data:

# This docker-compose file is used to build and test the container
services:
  foundry:
    # Run the container normally
    build:
      args:
        - VERSION=0.5.7
        # - HOTFIX_VERSION=0.5.8
      context: .
      dockerfile: Dockerfile
    image: felddy/foundryvtt:0.5.7
    hostname: felddy_foundryvtt
    init: true
    restart: "always"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - TIMEZONE=US/Eastern
      - FOUNDRY_ADMIN_KEY=atropos
      - FOUNDRY_GID=foundry
      - FOUNDRY_HOSTNAME=null
      - FOUNDRY_PROXY_PORT=null
      - FOUNDRY_PROXY_SSL=false
      - FOUNDRY_ROUTE_PREFIX=null
      - FOUNDRY_SSL_CERT=null
      - FOUNDRY_SSL_KEY=null
      - FOUNDRY_UID=foundry
      - FOUNDRY_UPDATE_CHANNEL=beta
      - FOUNDRY_UPNP=false
      - FOUNDRY_WORLD=null
    ports:
      - target: "30000"
        published: "30000"
        protocol: tcp
        mode: host

  foundry-version:
    # Run the container to collect version information
    image: felddy/foundryvtt:0.5.7
    init: true
    restart: "no"
    command: --version
