---
name: build

on:
  push:
  pull_request:
  repository_dispatch:
    types: [apb]

env:
  FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}
  FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
  IMAGE_NAME: felddy/foundryvtt
  PIP_CACHE_DIR: ~/.cache/pip
  PRE_COMMIT_CACHE_DIR: ~/.cache/pre-commit

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Store installed Python version
        run: |
          echo "::set-env name=PY_VERSION::"\
          "$(python -c "import platform;print(platform.python_version())")"
      - name: Cache linting environments
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.PIP_CACHE_DIR }}
            ${{ env.PRE_COMMIT_CACHE_DIR }}
          key: "lint-${{ runner.os }}-py${{ env.PY_VERSION }}-\
            ${{ hashFiles('**/requirements-test.txt') }}-\
            ${{ hashFiles('**/requirements.txt') }}-\
            ${{ hashFiles('**/.pre-commit-config.yaml') }}"
          restore-keys: |
            lint-${{ runner.os }}-py${{ env.PY_VERSION }}-
            lint-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
      - name: Set up pre-commit hook environments
        run: pre-commit install-hooks
      - name: Run pre-commit on all files
        run: pre-commit run --all-files
  build-normal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine image version
        id: get_ver
        run: |
          echo "##[set-output name=version;]$(./bump_version.sh show)"
      - name: Build docker image
        run: |
          version=${{ steps.get_ver.outputs.version }}
          docker build \
            --tag "$IMAGE_NAME:$version" \
            --build-arg GIT_COMMIT=$(git log -1 --format=%H) \
            --build-arg GIT_REMOTE=$(git remote get-url origin) \
            --build-arg VERSION="$version" \
            .
      - name: Save docker image artifact
        run: |
          mkdir dist
          version=${{ steps.get_ver.outputs.version }}
          docker save $IMAGE_NAME:$version | gzip > dist/image.tar.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: dist-normal
          path: dist
  build-pre-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine image version
        id: get_ver
        run: |
          echo "##[set-output name=version;]$(./bump_version.sh show)"
      - name: Build docker image
        run: |
          version=${{ steps.get_ver.outputs.version }}
          docker build \
            --tag "$IMAGE_NAME:$version" \
            --build-arg GIT_COMMIT=$(git log -1 --format=%H) \
            --build-arg GIT_REMOTE=$(git remote get-url origin) \
            --build-arg VERSION="$version" \
            --build-arg FOUNDRY_PASSWORD \
            --build-arg FOUNDRY_USERNAME \
            .
      - name: Save docker image artifact
        run: |
          mkdir dist
          version=${{ steps.get_ver.outputs.version }}
          docker save $IMAGE_NAME:$version | gzip > dist/image.tar.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: dist-pre-install
          path: dist
  test-normal:
    runs-on: ubuntu-latest
    needs: [build-normal]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Cache pip test requirements
        uses: actions/cache@v1
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: "${{ runner.os }}-pip-test-\
            ${{ hashFiles('**/requirements-test.txt') }}"
          restore-keys: |
            ${{ runner.os }}-pip-test-
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
      - name: Download docker image artifact
        uses: actions/download-artifact@v1
        with:
          name: dist-normal
      - name: Load docker image
        run: docker load < dist-normal/image.tar.gz
      - name: Set data directory permissions
        run: |
          chmod a+rwx data
      - name: Run tests
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: pytest --runslow
      - name: Upload data artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2.2.0
        with:
          name: data-normal
          path: data
  test-pre-install:
    runs-on: ubuntu-latest
    needs: [build-pre-install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache testing environments
        uses: actions/cache@v2
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: "test-${{ runner.os }}-\
            ${{ hashFiles('**/requirements-test.txt') }}"
          restore-keys: |
            test-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
      - name: Download docker image artifact
        uses: actions/download-artifact@v1
        with:
          name: dist-pre-install
      - name: Load docker image
        run: docker load < dist-pre-install/image.tar.gz
      - name: Set data directory permissions
        run: |
          chmod a+rwx data
      - name: Run tests
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: pytest --runslow
      - name: Upload data artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2.2.0
        with:
          name: data-pre-install
          path: data
