---

name: release

on:
  release:
    types: [published]

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: "Release test"
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
