---

name: release

on:
  release:
    types: [edited, published]

permissions:
  actions: read
  contents: read

jobs:
  config:
    name: "Config"
    uses: ./.github/workflows/_config.yml

  metadata:
    name: "Metadata"
    needs: [config]
    uses: ./.github/workflows/_metadata.yml
    with:
      image_name: ${{ needs.config.outputs.image_name }}
